title: Random Things I'm Interested In
description: Verbal unfiltered diarrhea from my journey through every day life.
author: Andrew Wang
github: https://github.com/wangandrewd
about: I'm an accidental founder of a startup. I used to do credit investing and have a background in CS. 
disqus_shortname: wangandrewd
google_analytics: UA-141250644-1
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/wang.andrew.d"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/andrew-w-73980246/"
    - icon: fa-github
      link: "https://github.com/agusmakmun"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/

url: "https://wangandrewd.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
